# Generated by Django 5.0.7 on 2024-07-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='low_quantity_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
