# Generated by Django 5.0.7 on 2024-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_products_low_quantity_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
