# Generated by Django 5.0.7 on 2024-08-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_sales_payment_mode_alter_sales_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='posApp.sales'),
        ),
    ]
