# Generated by Django 5.0.7 on 2024-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_products_buying_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='products',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='products',
            name='low_quantity_threshold',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
