# Generated by Django 5.0.7 on 2024-08-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_rename_category_id_products_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='low_quantity_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
