# Generated by Django 5.0.7 on 2024-08-12 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='low_quantity_threshold',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='products',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.sales'),
        ),
    ]
